version: '3.8'

services:
  analytics-service:
    build: .
    container_name: analytics-service
    ports:
      - "3002:3002"
      - "3003:3003"
      - "9091:9091"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://analytics_user:analytics_pass@postgres:5432/analytics_db
      - REDIS_HOST=redis
      - CLICKHOUSE_HOST=clickhouse
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres
      - redis
      - clickhouse
      - kafka
    volumes:
      - ./logs:/app/logs
    networks:
      - analytics-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: analytics-postgres
    environment:
      - POSTGRES_USER=analytics_user
      - POSTGRES_PASSWORD=analytics_pass
      - POSTGRES_DB=analytics_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - analytics-network

  redis:
    image: redis:7-alpine
    container_name: analytics-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - analytics-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: analytics-clickhouse
    environment:
      - CLICKHOUSE_DB=analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./migrations/clickhouse:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - analytics-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: analytics-kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "29092:29092"
    networks:
      - analytics-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: analytics-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  clickhouse-data: